services:
  - type: web
    name: your-app-name
    env: docker
    plan: free
    buildCommand: docker build -t your-app-name .
    startCommand: docker run -p 8080:8080 your-app-name
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mysql
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mysql
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mysql
          property: password
    healthCheckPath: /api/health
    autoDeploy: true

  - type: mysql
    name: mysql
    plan: free
    ipAllowList: []
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1 